name: Release and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Release') || contains(github.event.head_commit.message, 'release') || github.event_name == 'workflow_dispatch'

    steps:

      - name: Checkout code
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Extract version and artifact name
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          ARTIFACT=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "artifact=$ARTIFACT" >> $GITHUB_ENV

      - name: Set up Parameters
        run: |
          REPO=$(basename $GITHUB_REPOSITORY)
          echo "repository=$REPO" >> $GITHUB_ENV
          echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Build and Deploy
        run: mvn clean install package -U

      - name: Clean up target
        run: |
          mv target/${{ env.artifact }}-shaded.jar ${{ env.artifact }}.jar
          rm -rf target

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: echo "$token" | gh auth login --with-token
        env:
          token: ${{ env.token }}

      - name: Check for existing release
        run: |
          VERSION="${{ env.version }}"
          TAG_EXISTS=$(gh release view "$VERSION" --json tagName --jq ".tagName" 2>&1 || true)
          echo "TAG_EXISTS: $TAG_EXISTS"
          if [[ "$TAG_EXISTS" == *"release not found"* ]]; then
            echo "No release tag found for version $VERSION."
          else
            echo "Release tag found: $TAG_EXISTS"
            echo "Deleting release and tag: $TAG_EXISTS"
            gh release delete "$TAG_EXISTS" -y --cleanup-tag
            if git rev-parse "$TAG_EXISTS" >/dev/null 2>&1; then
              git tag -d "$TAG_EXISTS"
              git push origin --delete "$TAG_EXISTS"
            else
              echo "Tag $TAG_EXISTS not found locally."
            fi
          fi

      - name: Get latest existing release tag
        run: |
          TAG=$(git tag --sort=-creatordate | grep -v "${{ env.version }}" | head -n 1 || true)
          if [ -z "$TAG" ]; then
            echo "No previous tag found."
            CHANGELOG_URL="https://github.com/${{ github.repository }}/commits/${{ env.version }}"
          else
            echo "Previous tag: $TAG"
            CHANGELOG_URL="https://github.com/${{ github.repository }}/compare/$TAG...${{ env.version }}"
          fi
          echo "tag=$TAG" >> $GITHUB_ENV
          echo "changelog_url=$CHANGELOG_URL" >> $GITHUB_ENV

      - name: Calculate Hashes
        run: |
          FILE=${{ env.artifact }}.jar
          MD5=$(md5sum "$FILE" | cut -d ' ' -f 1)
          SHA1=$(sha1sum "$FILE" | cut -d ' ' -f 1)
          SHA256=$(sha256sum "$FILE" | cut -d ' ' -f 1)
          echo "md5=$MD5" >> $GITHUB_ENV
          echo "sha1=$SHA1" >> $GITHUB_ENV
          echo "sha256=$SHA256" >> $GITHUB_ENV
          echo "file=$FILE" >> $GITHUB_ENV

      - name: Create new release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ${{ env.file }}
          tag_name: ${{ env.version }}
          name: "${{ env.repository}} - Release ${{ env.version }}"
          body: |
            **Full Changelog**: ${{ env.changelog_url }}

            ## Checksums:

            - MD5: ${{ env.md5 }}
            - SHA1: ${{ env.sha1 }}
            - SHA256: ${{ env.sha256 }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Rename JAR file
        run: mv "${{ env.file }}" "MyFritz-Resolver.jar"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            mcmodersd/myfritz-resolver:${{ env.version }}
            mcmodersd/myfritz-resolver:latest